[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.idea
    | \.vscode
    | \assets
    | \tests
    | __pycache__
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
honor_noqa = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.pytest.ini_options]
addopts = "--capture=tee-sys"
